[project]
name = "code-challange-indicium"
version = "0.1.0"
description = "Code challange for Indicium hiring process. By Fernando Stahelin"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.7.1",
]
